server:
  port: 6666
  use-forward-headers: true
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 Database 配置
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/halo-test/db/halo
    # url: jdbc:h2:file:E:/Develop/.halo/db/halo
    username: root
    password: root

    # MySQL 配置
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://127.0.0.1:3306/halo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  #  username: root
  #  password: root

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    favicon:
      enabled: false
  cache:
    type: none
logging:
  level:
    run.halo.app: DEBUG
    org.hibernate: ERROR
  path: ${user.home}/halo-test/logs

halo:
  doc-disabled: false

